name: Blazing Food Build
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checking out code
      uses: actions/checkout@v2
    - name: Instelling .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.411
        include-prerelease: false
    - name: Restoring Nuget Packages
      run: dotnet restore
    - name: Building Project
      run: dotnet build --no-restore
    - name: Running Tests
      run: dotnet test --no-build --verbosity normal
